### ISSUE TITLE
`MIndenter/performIndenting` error

### ISSUE THREAD

**Issue by casperdcl** [davidvarga/MBeautifier#99]
Running `MBeautifier` on https://github.com/davidvarga/MBeautifier/blob/01c8e14/%2BMBeautifier/DirectiveChangeType.m:

```
Cell contents indices must be greater than 0

Error in MBeautifier.MIndenter/performIndenting (line 133)
                            if (strcmp(stack{end}, 'function'))
Error in MBeautify.formatFileNoEditor (line 53)
            text = indenter.performIndenting(text);
```

**Comment by davidvarga** [comment]
Fixed :)

**Comment by casperdcl** [comment]
Great @davidvarga! Though `MBeautifier` still fails to run on its own codebase because of #98
